[package]
name = "rubiks-cube-robot-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.1.0"
ev3dev-lang-rust = "0.14.0"

[profile.release]
lto = true
strip = "debuginfo"
